name: Deploy with Docker Compose

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: course.prafdin.ru
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2431
        script: |
          cd /home/ubuntu/app
          git pull
          docker compose down
          docker compose up -d --build
          echo "✅ Deployment completed"